Models/Gig.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyGigHub.Models
{
    public class Gig
    {
        public int Id { get; set; }

        public ApplicationUser Artist { get; set; }
        [Required]
        public string ArtistId { get; set; }

        public DateTime DateTime { get; set; }

        [Required]
        [StringLength(255)]
        public String Venue { get; set; }

        public Genre Genre { get; set; }
        [Required]
        public byte GenreId { get; set; }
    }
}

Controllers/GigController.cs
using Microsoft.AspNet.Identity;
using MyGigHub.Models;
using MyGigHub.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyGigHub.Controllers
{
    public class GigController : Controller
    {
        private ApplicationDbContext _Context;
        public GigController()
        {
            _Context = new ApplicationDbContext();
        }

        // GET: Gig
        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new GigFormViewModel();
            viewModel.Genres = _Context.Genres.ToList();
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GigFormViewModel viewModel)
        {
            viewModel.Genres = _Context.Genres.ToList();
            if (!ModelState.IsValid)
                return View("Create", viewModel);
            var gig = new Gig
            {
                ArtistId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                GenreId = viewModel.Genre,
                Venue = viewModel.Venue
            };
            _Context.Gigs.Add(gig);
            _Context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Gig/Create.cshtml
@model MyGigHub.ViewModel.GigFormViewModel

@{
    /**/

    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Gig"))
{
    @Html.AntiForgeryToken()
    <a class="alert">All field are <strong>required</strong>.</a>
        <div class="form-group">
            @Html.LabelFor(m => m.Venue)
            @Html.TextBoxFor(m => m.Venue, new { @class = "form-control" ,autofocus= "autofocus" })
            @Html.ValidationMessageFor(m=>m.Venue)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control" , placeholder="eg 10 JAN 2018" })
            @Html.ValidationMessageFor(m=>m.Date)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Time)
            @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
            @Html.ValidationMessageFor(m=>m.Time)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Genre)
            @Html.DropDownListFor(m => m.Genre, new SelectList(Model.Genres, "Id", "Name"), "", new { @class = "form-control" })
            @Html.ValidationMessageFor(m=>m.Genre)
        </div>
        <button type="submit" class="btn btn-primary">Save</button>


}